version: 2
jobs:
  lint:
    docker:
      - image: bufbuild/buf:1.1.0
    steps:
      - checkout
      - run: buf lint proto
  breaking:
    docker:
      - image: bufbuild/buf:1.1.0
    steps:
      - checkout
      - run: buf breaking proto --against https://github.com/bufbuild/buf-examples.git#branch=main,ref=HEAD~1,subdir=proto

workflows:
  version: 2
  protobuf_check:
    jobs:
      - lint
      - breaking
