name: CI
on: push
jobs:
  lint-and-breaking-change-detection:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - name: Checkout
        uses: actions/checkout@v2
      # Install the `buf` CLI
      - name: Setup
        uses: bufbuild/buf-setup-action@v0.5.0
        with:
          version: '1.1.0'
      # Lint the Buf module in the `proto` directory
      - name: Lint
        uses: bufbuild/buf-lint-action@v1
        with:
          input: proto
      # Detect breaking changes for the Buf module in the `proto` directory
      # against the current `main` branch
      - name: Breaking change detection against `main`
        uses: bufbuild/buf-breaking-action@v1
        with:
          input: proto
          against: https://github.com/bufbuild/buf-examples.git#branch=main,ref=HEAD~1,subdir=proto
