name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: `buf` CLI setup
        uses: buf-setup-action@v0.5.0
      - name: Lint Protobuf sources
        uses: buf-lint-action@v1
        working-directory: github-actions
      - name: Run breaking change detection against `main`
        uses: buf-breaking-action@v1
        working-directory: github-actions
        with:
          against: ../.git#branch=main
